var defaultSites =
{
  "ABC.es": "abc.es",
  "Adweek": "adweek.com",
  "Algemeen Dagblad (+ regional)": "###_nl_ad_region",
  "Alma Talent (Finland)": "###_fi_alma_talent",
  "Alternatives Economiques": "alternatives-economiques.fr",
  "Ámbito": "ambito.com",
  "American Affairs": "americanaffairsjournal.org",
  "American Banker": "americanbanker.com",
  "Atavist Magazine": "atavist.com",
  "Australia News Corp": "###_au_news_corp",
  "Australian Community Media (daily)": "###_au_comm_media",
  "Australian Provincial Newspapers (daily) (opt-in)": "###_au_prov_news",
  "Baltimore Sun": "baltimoresun.com",
  "Barron's": "barrons.com",
  "BBC History Extra": "historyextra.com",
  "Belfast Telegraph (opt-in)": "belfasttelegraph.co.uk",
  "Berlingske": "berlingske.dk",
  "Bloomberg": "bloomberg.com",
  "Bloomberg Quint (free articles only)": "bloombergquint.com",
  "Brisbane Times": "brisbanetimes.com.au",
  "Business Insider": "businessinsider.com",
  "Business Standard": "business-standard.com",
  "Caixin Global": "caixinglobal.com",
  "Challenges": "challenges.fr",
  "Charlie Hebdo": "charliehebdo.fr",
  "Chemical & Engineering News": "cen.acs.org",
  "Chicago Tribune": "chicagotribune.com",
  "Chronicle of Higher Education": "chronicle.com",
  "Cicero.de": "cicero.de",
  "Clarín": "clarin.com",
  "Commentary Magazine": "commentarymagazine.com",
  "CommonWealth Magazine Taiwan": "cw.com.tw",
  "Correio da Manhã": "cmjornal.pt",
  "Corriere Della Sera": "corriere.it",
  "Crain's Chicago Business": "chicagobusiness.com",
  "Dagblad van het Noorden": "dvhn.nl",
  "Dagens Nyheter": "dn.se",
  "Daily Press": "dailypress.com",
  "Dark Reading": "darkreading.com",
  "De Tijd": "tijd.be",
  "DeMorgen": "demorgen.be",
  "Deutsche Wirtschafts Nachrichten": "deutsche-wirtschafts-nachrichten.de",
  "Diario Financiero": "df.cl",
  "Die Zeit": "zeit.de",
  "Digiday": "digiday.com",
  "Discover Magazine": "discovermagazine.com",
  "Domani": "editorialedomani.it",
  "El Comercio": "elcomercio.pe",
  "El Confidencial": "elconfidencial.com",
  "El Diario.es": "eldiario.es",
  "El Mercurio": "elmercurio.com",
  "El Mercurio de Valparaíso": "mercuriovalpo.cl",
  "El Mundo": "elmundo.es",
  "El País": "elpais.com",
  "El Periódico (de Catalunya)": "elperiodico.com",
  "Encyclopedia Britannica": "britannica.com",
  "Esprit": "esprit.presse.fr",
  "EUobserver": "euobserver.com",
  "Eureka Report": "eurekareport.com.au",
  "Exame": "exame.abril.com.br",
  "Expansión": "expansion.com",
  "Financial News": "fnlondon.com",
  "Financial Post": "financialpost.com",
  "Financial Times": "ft.com",
  "Financieele Dagblad (fd.nl)": "fd.nl",
  "First Things": "firstthings.com",
  "Folha de S. Paulo": "folha.uol.com.br",
  "Follow the Money (ftm.nl)": "ftm.nl",
  "Foreign Affairs": "foreignaffairs.com",
  "Foreign Policy": "foreignpolicy.com",
  "Fortune": "fortune.com",
  "Frankfurter Allgemeine Zeitung": "faz.net",
  "Freie Presse": "freiepresse.de",
  "Funke Mediengruppe": "###_de_funke_medien",
  "Gazet van Antwerpen": "gva.be",
  "GElocal.it": "gelocal.it",
  "Gestión": "gestion.pe",
  "Glassdoor": "glassdoor.com",
  "Globes": "globes.co.il",
  "Griffith Review": "griffithreview.com",
  "Groene Amsterdammer": "groene.nl",
  "Groupe EBRA (France)": "###_fr_groupe_ebra",
  "Groupe La Dépêche (France)": "###_fr_groupe_la_depeche",
  "Groupe Rossel (France/Belgium)": "###_fr_be_groupe_rossel",
  "Grupo Vocento (Spain, regional daily)": "###_es_grupo_vocento",
  "Haaretz English": "haaretz.com",
  "Haaretz": "haaretz.co.il",
  "Handelsblatt": "handelsblatt.com",
  "Harper's Magazine": "harpers.org",
  "Hartford Courant": "courant.com",
  "Harvard Business Review": "hbr.org",
  "Harvard Business Review Taiwan": "hbrtaiwan.com",
  "Helsingin Sanomat": "hs.fi",
  "Humo.be": "humo.be",
  "Il Fatto Quotidiano": "ilfattoquotidiano.it",
  "Il Manifesto": "ilmanifesto.it",
  "Il Messaggero (+ regional)": "###_it_ilmessaggero",
  "Il Resto del Carlino": "ilrestodelcarlino.it",
  "Il Secolo XIX": "ilsecoloxix.it",
  "Inc.com": "inc.com",
  "Inkl": "inkl.com",
  "Intelligent Investor": "intelligentinvestor.com.au",
  "Irish Independent (opt-in)": "independent.ie",
  "Knack.be": "knack.be",
  "Krautreporter.de": "krautreporter.de",
  "Kurier.at": "kurier.at",
  "L'Obs": "nouvelobs.com",
  "L'Opinion": "lopinion.fr",
  "L'Orient-Le Jour": "lorientlejour.com",
  "L'Usine Nouvelle": "usinenouvelle.com",
  "La Croix": "la-croix.com",
  "La Estrella de Valparaíso": "estrellavalpo.cl",
  "La Nación": "lanacion.com.ar",
  "La Nueva España": "lne.es",
  "La Nuova Sardegna": "lanuovasardegna.it",
  "La Repubblica": "repubblica.it",
  "La Segunda": "lasegunda.com",
  "La Stampa": "lastampa.it",
  "La Tercera": "latercera.com",
  "La Vanguardia": "lavanguardia.com",
  "Le Devoir": "ledevoir.com",
  "Le Journal du Dimanche": "lejdd.fr",
  "Le Journal du Net": "journaldunet.com",
  "Le Parisien": "leparisien.fr",
  "Le Scienze": "lescienze.it",
  "Le Un": "le1hebdo.fr",
  "Leeuwarder Courant": "lc.nl",
  "Les Échos": "lesechos.fr",
  "Libération (free articles only)": "liberation.fr",
  "LimesOnline": "limesonline.com",
  "LiveMint": "livemint.com",
  "Loeb Classical Library": "loebclassics.com",
  "London Review of Books": "lrb.co.uk",
  "Los Angeles Business Journal": "labusinessjournal.com",
  "Los Angeles Times": "latimes.com",
  "Madsack Mediengruppe (Germany)": "###_de_madsack",
  "MarketWatch": "marketwatch.com",
  "Medium (all sites)": "medium.com",
  "Mexico News Daily": "mexiconewsdaily.com",
  "Miami Herald": "miamiherald.com",
  "MIT Sloan Management Review": "sloanreview.mit.edu",
  "MIT Technology Review": "technologyreview.com",
  "Modern Healthcare": "modernhealthcare.com",
  "National Geographic USA": "nationalgeographic.com",
  "Mountain View Voice": "mv-voice.com",
  "National Post": "nationalpost.com",
  "National Review": "nationalreview.com",
  "Nautilus": "nautil.us",
  "Neue Zürcher Zeitung": "nzz.ch",
  "New Left Review": "newleftreview.org",
  "New York Magazine (+ Curbed, Grub Street, The Cut & Vulture)": "###_usa_nymag",
  "New Zealand Herald": "nzherald.co.nz",
  "Newsweek": "newsweek.com",
  "Nikkei Asian Review": "asia.nikkei.com",
  "Noordhollands Dagblad": "noordhollandsdagblad.nl",
  "NRC Handelsblad": "nrc.nl",
  "O Estado de S. Paulo": "estadao.com.br",
  "O Globo": "globo.com",
  "Observador.pt": "observador.pt",
  "Orange County Register": "ocregister.com",
  "Orlando Sentinel": "orlandosentinel.com",
  "Palo Alto Online": "paloaltoonline.com",
  "Paris Match": "parismatch.com",
  "Parool": "parool.nl",
  "Philosophy Now": "philosophynow.org",
  "Piqd.de": "piqd.de",
  "Pittsburgh Post Gazette": "post-gazette.com",
  "Prospect Magazine": "prospectmagazine.co.uk",
  "Quartz (free articles only)": "qz.com",
  "Quora": "quora.com",
  "Quotidiano.net": "quotidiano.net",
  "Republic.ru": "republic.ru",
  "Rolling Stone": "rollingstone.com",
  "Ruhr Nachrichten": "ruhrnachrichten.de",
  "Sächsische Zeitung": "saechsische.de",
  "San Diego Union Tribune": "sandiegouniontribune.com",
  "San Francisco Chronicle": "sfchronicle.com",
  "Schweriner Volkszeitung": "svz.de",
  "Science & Vie": "science-et-vie.com",
  "Sciences et Avenir": "sciencesetavenir.fr",
  "Scientific American (free articles only)": "scientificamerican.com",
  "Scribd (documents only)": "scribd.com",
  "Seeking Alpha": "seekingalpha.com",
  "Slader": "slader.com",
  "Slate": "slate.com",
  "SOFREP": "sofrep.com",
  "South China Morning Post": "scmp.com",
  "Star Tribune": "startribune.com",
  "Statista": "statista.com",
  "Stock News": "stocknews.com",
  "Stratfor": "stratfor.com",
  "Sud Ouest": "sudouest.fr",
  "Süddeutsche Zeitung": "sueddeutsche.de",
  "SunSentinel": "sun-sentinel.com",
  "Tech in Asia": "techinasia.com",
  "Telegraaf": "telegraaf.nl",
  "The Age": "theage.com.au",
  "The American Interest": "the-american-interest.com",
  "The Atlantic": "theatlantic.com",
  "The Australian Financial Review": "afr.com",
  "The Boston Globe (opt-in)": "bostonglobe.com",
  "The Business Journals": "bizjournals.com",
  "The Christian Science Monitor": "csmonitor.com",
  "The Daily Beast (free articles only)": "thedailybeast.com",
  "The Denver Post": "denverpost.com",
  "The Diplomat": "thediplomat.com",
  "The Economist": "economist.com",
  "The Fresno Bee": "fresnobee.com",
  "The Globe and Mail": "theglobeandmail.com",
  "The Hill Times": "hilltimes.com",
  "The Hindu": "thehindu.com",
  "The Hindu BusinessLine": "thehindubusinessline.com",
  "The Irish Times": "irishtimes.com",
  "The Japan Times": "japantimes.co.jp",
  "The Jerusalem Post": "jpost.com",
  "The Logic": "thelogic.co",
  "The Marker": "themarker.com",
  "The Mercury News": "mercurynews.com",
  "The Morning Call": "mcall.com",
  "The Nation": "thenation.com",
  "The New Republic": "newrepublic.com",
  "The New Statesman": "newstatesman.com",
  "The New York Review of Books": "nybooks.com",
  "The New York Times": "nytimes.com",
  "The New Yorker": "newyorker.com",
  "The News-Gazette": "news-gazette.com",
  "The Philadelphia Inquirer": "inquirer.com",
  "The Point Magazine": "thepointmag.com",
  "The Sacramento Bee": "sacbee.com",
  "The Saturday Paper": "thesaturdaypaper.com.au",
  "The Seattle Times": "seattletimes.com",
  "The Spectator (UK)": "spectator.co.uk",
  "The Spectator Australia": "spectator.com.au",
  "The Spectator USA": "spectator.us",
  "The Sydney Morning Herald": "smh.com.au",
  "The Telegraph": "telegraph.co.uk",
  "The Times": "thetimes.co.uk",
  "The Times Literary Supplement": "the-tls.co.uk",
  "The Toronto Star (+ local TorStar sites)": "###_ca_torstar",
  "The Wall Street Journal (not Chinese)": "wsj.com",
  "The Washington Post": "washingtonpost.com",
  "The West Australian (+ regional)": "thewest.com.au",
  "Times Higher Education": "timeshighereducation.com",
  "Towards Data Science": "towardsdatascience.com",
  "Trouw": "trouw.nl",
  "Valeurs Actuelles": "valeursactuelles.com",
  "Vanity Fair": "vanityfair.com",
  "Variety": "variety.com",
  "Volkskrant": "volkskrant.nl",
  "WAtoday": "watoday.com.au",
  "Winston-Salem Journal": "journalnow.com",
  "Wired": "wired.com",
  "WirtschaftsWoche": "wiwo.de",
  "World Politics Review": "worldpoliticsreview.com",
  "* Block Paywall-scripts (opt-in to custom sites to enable also for non-listed sites)": "###",
  "Amp-access": "cdn.ampproject.org",
  "BlueConic": "blueconic.net",
  "Cxense": "cxense.com",
  "Evolok": "evolok.net",
  "MatherAnalytics": "matheranalytics.com",
  "NewsMemory": "newsmemory.com",
  "OneCount": "onecount.net",
  "Pelcro": "pelcro.com",
  "Piano.io": "piano.io",
  "Poool.fr": "poool.fr",
  "Qiota": "qiota.com",
  "TinyPass": "tinypass.com",
  "TribDss": "tribdss.com",
  "* BPC settings": "###",
  "Show options on update": "#options_on_update"
}
