var defaultSites =
{
  "360Dx": "360dx.com",
  "ABC.es": "abc.es",
  "Adweek": "adweek.com",
  "Algemeen Dagblad (+ regional)": "###_nl_ad_region",
  "Alma Talent (Finland)": "###_fi_alma_talent",
  "Alternatives Economiques": "alternatives-economiques.fr",
  "Ámbito": "ambito.com",
  "American Affairs": "americanaffairsjournal.org",
  "American Banker": "americanbanker.com",
  "Apollo Magazine": "apollo-magazine.com",
  "Asia Times": "asiatimes.com",
  "Atavist Magazine": "atavist.com",
  "Atlantico.fr": "atlantico.fr",
  "Augsburger Allgemeine": "augsburger-allgemeine.de",
  "Australia News Corp": "###_au_news_corp",
  "Australian Community Media (daily)": "###_au_comm_media",
  "Australian Provincial Newspapers (daily) (opt-in)": "###_au_prov_news",
  "Barron's": "barrons.com",
  "BBC History Extra": "historyextra.com",
  "Belfast Telegraph (opt-in)": "belfasttelegraph.co.uk",
  "Berliner Zeitung": "berliner-zeitung.de",
  "Berlingske": "berlingske.dk",
  "Billboard": "billboard.com",
  "Bloomberg": "bloomberg.com",
  "Bloomberg Quint (free articles only)": "bloombergquint.com",
  "Brisbane Times": "brisbanetimes.com.au",
  "Business Insider": "businessinsider.com",
  "Business Standard": "business-standard.com",
  "Caixin Global": "caixinglobal.com",
  "Challenges": "challenges.fr",
  "Charlie Hebdo": "charliehebdo.fr",
  "Chemical & Engineering News": "cen.acs.org",
  "Chronicle of Higher Education": "chronicle.com",
  "Cicero.de": "cicero.de",
  "Clarín": "clarin.com",
  "Commentary Magazine": "commentarymagazine.com",
  "CommonWealth Magazine Taiwan": "cw.com.tw",
  "Correio da Manhã": "cmjornal.pt",
  "Corriere Della Sera": "corriere.it",
  "Crain's Business": "###_usa_crainsbiz",
  "Dagblad van het Noorden": "dvhn.nl",
  "Dagens Industri": "di.se",
  "Dagens Nyheter": "dn.se",
  "Daily Nation": "nation.africa",
  "Dark Reading": "darkreading.com",
  "De Tijd": "tijd.be",
  "DeMorgen": "demorgen.be",
  "Deutsche Wirtschafts Nachrichten": "deutsche-wirtschafts-nachrichten.de",
  "Diario de Ibiza": "diariodeibiza.es",
  "Diario de Mallorca": "diariodemallorca.es",
  "Diario Financiero": "df.cl",
  "Die Rheinpfalz": "rheinpfalz.de",
  "Die Zeit": "zeit.de",
  "Digiday": "digiday.com",
  "Discover Magazine": "discovermagazine.com",
  "Domani": "editorialedomani.it",
  "El Comercio": "elcomercio.pe",
  "El Confidencial": "elconfidencial.com",
  "El Diario.es": "eldiario.es",
  "El Español": "elespanol.com",
  "El Mercurio": "elmercurio.com",
  "El Mercurio de Valparaíso": "mercuriovalpo.cl",
  "El Mundo": "elmundo.es",
  "El País": "elpais.com",
  "El Periódico (de Catalunya)": "elperiodico.com",
  "Encyclopedia Britannica": "britannica.com",
  "Entrepreneur": "entrepreneur.com",
  "Esprit": "esprit.presse.fr",
  "EUobserver": "euobserver.com",
  "Eureka Report": "eurekareport.com.au",
  "Exame": "exame.com",
  "Expansión": "expansion.com",
  "Faro de Vigo": "farodevigo.es",
  "Financial News": "fnlondon.com",
  "Financial Post": "financialpost.com",
  "Financial Times (not Chinese)": "ft.com",
  "Financieele Dagblad (fd.nl)": "fd.nl",
  "First Things": "firstthings.com",
  "Folha de S. Paulo": "###_br_folha",
  "Follow the Money (ftm.nl)": "ftm.nl",
  "Foreign Affairs": "foreignaffairs.com",
  "Foreign Policy": "foreignpolicy.com",
  "Fortune": "fortune.com",
  "Frankfurter Allgemeine Zeitung": "faz.net",
  "Freie Presse": "freiepresse.de",
  "Funke Mediengruppe": "###_de_funke_medien",
  "Gannett Group (local USA Today) (opt-in to custom sites)": "###_usa_gannett",
  "Gazet van Antwerpen": "gva.be",
  "GElocal.it": "gelocal.it",
  "GenomeWeb": "genomeweb.com",
  "Gestión": "gestion.pe",
  "Glassdoor": "glassdoor.com",
  "Globes": "globes.co.il",
  "Griffith Review": "griffithreview.com",
  "Groene Amsterdammer": "groene.nl",
  "Groupe EBRA (France)": "###_fr_groupe_ebra",
  "Groupe La Dépêche (France)": "###_fr_groupe_la_depeche",
  "Groupe Rossel (France/Belgium)": "###_fr_be_groupe_rossel",
  "Grupo Abril": "abril.com.br",
  "Grupo Vocento (Spain, regional daily)": "###_es_grupo_vocento",
  "Haaretz English": "haaretz.com",
  "Haaretz": "haaretz.co.il",
  "Handelsblatt": "handelsblatt.com",
  "Harper's Magazine": "harpers.org",
  "Harvard Business Review": "hbr.org",
  "Harvard Business Review Taiwan": "hbrtaiwan.com",
  "Helsingin Sanomat": "hs.fi",
  "Hindustan Times": "hindustantimes.com",
  "Honolulu Star-Advertiser": "staradvertiser.com",
  "Houston Chronicle": "houstonchronicle.com",
  "Humo.be": "humo.be",
  "Il Fatto Quotidiano": "ilfattoquotidiano.it",
  "Il Giorno": "ilgiorno.it",
  "Il Manifesto": "ilmanifesto.it",
  "Il Messaggero (+ regional)": "###_it_ilmessaggero",
  "Il Resto del Carlino": "ilrestodelcarlino.it",
  "Il Secolo XIX": "ilsecoloxix.it",
  "Inc.com": "inc.com",
  "Inkl": "inkl.com",
  "Intelligent Investor": "intelligentinvestor.com.au",
  "Irish Independent (opt-in)": "independent.ie",
  "Knack.be": "knack.be",
  "Krautreporter.de": "krautreporter.de",
  "Kurier.at": "kurier.at",
  "L'Express": "lexpress.fr",
  "L'Obs": "nouvelobs.com",
  "L'Oeil de la Photographie": "loeildelaphotographie.com",
  "L'Opinion": "lopinion.fr",
  "L'Orient-Le Jour": "lorientlejour.com",
  "L'Usine Nouvelle": "usinenouvelle.com",
  "La Croix": "la-croix.com",
  "La Estrella de Valparaíso": "estrellavalpo.cl",
  "La Nación": "lanacion.com.ar",
  "La Nazione": "lanazione.it",
  "La Nouvelle République du Centre-Ouest": "lanouvellerepublique.fr",
  "La Nueva España": "lne.es",
  "La Nuova Sardegna": "lanuovasardegna.it",
  "La Provincia": "laprovincia.es",
  "La Repubblica": "repubblica.it",
  "La Segunda": "lasegunda.com",
  "La Stampa": "lastampa.it",
  "La Tercera": "latercera.com",
  "La Tribune": "latribune.fr",
  "La Vanguardia": "lavanguardia.com",
  "Law.com (free articles only)": "law.com",
  "Le Devoir": "ledevoir.com",
  "Le Journal du Dimanche": "lejdd.fr",
  "Le Journal du Net": "journaldunet.com",
  "Le Parisien": "leparisien.fr",
  "Le Scienze": "lescienze.it",
  "Le Télégramme": "letelegramme.fr",
  "Le Un": "le1hebdo.fr",
  "Leeuwarder Courant": "lc.nl",
  "Les Échos": "lesechos.fr",
  "Levante-EMV": "levante-emv.com",
  "Libération (free articles only)": "liberation.fr",
  "LimesOnline": "limesonline.com",
  "LiveMint": "livemint.com",
  "Loeb Classical Library": "loebclassics.com",
  "London Review of Books": "lrb.co.uk",
  "Los Angeles Business Journal": "labusinessjournal.com",
  "Los Angeles Times": "latimes.com",
  "Madsack Mediengruppe (Germany)": "###_de_madsack",
  "MarketWatch": "marketwatch.com",
  "McClatchy Group": "###_usa_mcc",
  "Mediahuis Nederland Regional": "###_nl_mediahuis_region",
  "MediaNama": "medianama.com",
  "Medium": "medium.com",
  "Medium custom domains": "###_medium_custom",
  "Mexico News Daily": "mexiconewsdaily.com",
  "MIT Sloan Management Review": "sloanreview.mit.edu",
  "MIT Technology Review": "technologyreview.com",
  "Modern Healthcare": "modernhealthcare.com",
  "National Geographic USA": "nationalgeographic.com",
  "Mountain View Voice": "mv-voice.com",
  "National Post": "nationalpost.com",
  "National Review": "nationalreview.com",
  "Nautilus": "nautil.us",
  "Neue Osnabrücker Zeitung": "noz.de",
  "Neue Zürcher Zeitung": "nzz.ch",
  "New Left Review": "newleftreview.org",
  "New York Magazine (+ Curbed, Grub Street, The Cut & Vulture)": "###_usa_nymag",
  "New Zealand Herald": "nzherald.co.nz",
  "Newsday": "newsday.com",
  "Newsweek": "newsweek.com",
  "Nikkei Asian Review": "asia.nikkei.com",
  "NK News (free articles only)": "nknews.org",
  "Nordwest Zeitung": "nwzonline.de",
  "NRC Handelsblad": "nrc.nl",
  "NyTeknik": "nyteknik.se",
  "O Estado de S. Paulo": "estadao.com.br",
  "O Globo (& Valor Econômico)": "globo.com",
  "Observador.pt": "observador.pt",
  "Orange County Register": "ocregister.com",
  "Palo Alto Online": "paloaltoonline.com",
  "Paris Match": "parismatch.com",
  "Parool": "parool.nl",
  "Philosophy Now": "philosophynow.org",
  "Piqd.de": "piqd.de",
  "Pittsburgh Post Gazette": "post-gazette.com",
  "Política Exterior": "politicaexterior.com",
  "Precision Oncology News": "precisiononcologynews.com",
  "Prospect Magazine": "prospectmagazine.co.uk",
  "Rhein-Zeitung": "rhein-zeitung.de",
  "Quartz (free articles only)": "qz.com",
  "Quora": "quora.com",
  "Quotidiano.net": "quotidiano.net",
  "Republic.ru": "republic.ru",
  "Reuters": "reuters.com",
  "Rolling Stone": "rollingstone.com",
  "Ruhr Nachrichten": "ruhrnachrichten.de",
  "Sächsische Zeitung": "saechsische.de",
  "San Diego Union Tribune": "sandiegouniontribune.com",
  "San Francisco Chronicle": "sfchronicle.com",
  "Schleswig-Holsteinischer Zeitungsverlag": "shz.de",
  "Schweriner Volkszeitung": "svz.de",
  "Science & Vie": "science-et-vie.com",
  "Sciences et Avenir": "sciencesetavenir.fr",
  "Scientific American (free articles only)": "scientificamerican.com",
  "Scribd (documents only)": "scribd.com",
  "Seeking Alpha": "seekingalpha.com",
  "Slader": "slader.com",
  "Slate": "slate.com",
  "SOFREP": "sofrep.com",
  "South China Morning Post": "scmp.com",
  "Sports Illustrated": "si.com",
  "Star Tribune": "startribune.com",
  "Statista": "statista.com",
  "Stock News": "stocknews.com",
  "Stratfor": "stratfor.com",
  "Sud Ouest": "sudouest.fr",
  "Süddeutsche Zeitung": "sueddeutsche.de",
  "Tech in Asia": "techinasia.com",
  "Telegraaf": "telegraaf.nl",
  "The Age": "theage.com.au",
  "The American Interest": "the-american-interest.com",
  "The Art Newspaper": "theartnewspaper.com",
  "The Athletic": "###_usa_theathletic",
  "The Atlanta Journal-Constitution": "ajc.com",
  "The Atlantic": "theatlantic.com",
  "The Australian Financial Review": "afr.com",
  "The Boston Globe": "bostonglobe.com",
  "The Business Journals": "bizjournals.com",
  "The Christian Science Monitor": "csmonitor.com",
  "The Daily Beast (free articles only)": "thedailybeast.com",
  "The Dallas Morning News": "dallasnews.com",
  "The Denver Post": "denverpost.com",
  "The Diplomat": "thediplomat.com",
  "The Economic Times (ET Prime)": "###_economictimes",
  "The Economist": "economist.com",
  "The Globe and Mail": "theglobeandmail.com",
  "The Hill Times": "hilltimes.com",
  "The Hindu": "thehindu.com",
  "The Hindu BusinessLine": "thehindubusinessline.com",
  "The Irish Times": "irishtimes.com",
  "The Japan Times": "japantimes.co.jp",
  "The Jerusalem Post": "jpost.com",
  "The Logic": "thelogic.co",
  "The Marker": "themarker.com",
  "The Mercury News": "mercurynews.com",
  "The Nation": "thenation.com",
  "The New Atlantis": "thenewatlantis.com",
  "The New Republic": "newrepublic.com",
  "The New Statesman": "newstatesman.com",
  "The New York Review of Books": "nybooks.com",
  "The New York Times": "nytimes.com",
  "The New Yorker": "newyorker.com",
  "The Philadelphia Inquirer": "inquirer.com",
  "The Point Magazine": "thepointmag.com",
  "The Saturday Paper": "thesaturdaypaper.com.au",
  "The Seattle Times": "seattletimes.com",
  "The Spectator (UK)": "spectator.co.uk",
  "The Spectator Australia": "spectator.com.au",
  "The Spectator USA": "spectator.us",
  "The Sydney Morning Herald": "smh.com.au",
  "The Telegraph": "telegraph.co.uk",
  "The Times": "thetimes.co.uk",
  "The Times Literary Supplement": "the-tls.co.uk",
  "The Toronto Star (+ local TorStar sites)": "###_ca_torstar",
  "The Wall Street Journal (not Chinese)": "wsj.com",
  "The Washington Post": "washingtonpost.com",
  "The West Australian (+ regional)": "thewest.com.au",
  "The Wrap": "thewrap.com",
  "Time Magazine": "time.com",
  "Times Higher Education": "timeshighereducation.com",
  "Times of India": "###_timesofindia",
  "Towards Data Science": "towardsdatascience.com",
  "Tribune Publishing Company": "###_usa_tribune",
  "Trouw": "trouw.nl",
  "USA Today": "usatoday.com",
  "Valeurs Actuelles": "valeursactuelles.com",
  "Vanity Fair": "vanityfair.com",
  "Variety": "variety.com",
  "VeloNews": "velonews.com",
  "VentureBeat": "venturebeat.com",
  "Volkskrant": "volkskrant.nl",
  "WAtoday": "watoday.com.au",
  "Winston-Salem Journal": "journalnow.com",
  "Wired": "wired.com",
  "WirtschaftsWoche": "wiwo.de",
  "World Politics Review": "worldpoliticsreview.com",
  "* Block Paywall-scripts (opt-in to custom sites to enable also for non-listed sites)": "###",
  "Amp-access": "cdn.ampproject.org",
  "BlueConic": "blueconic.net",
  "Cxense": "cxense.com",
  "Evolok": "evolok.net",
  "MatherAnalytics": "matheranalytics.com",
  "NewsMemory": "newsmemory.com",
  "OneCount": "onecount.net",
  "Pelcro": "pelcro.com",
  "Piano.io": "piano.io",
  "Poool.fr": "poool.fr",
  "Qiota": "qiota.com",
  "TinyPass": "tinypass.com",
  "TribDss": "tribdss.com",
  "* BPC settings": "###",
  "Show options on update": "#options_on_update",
  "Restore opt-in for custom sites (on reload; Chrome-only)": "#options_restore_custom",
  "Barron's - no Googlebot (http error 500)": "#options_disable_gb_barrons",
  "The Wall Street Journal - no Googlebot (http error 500)": "#options_disable_gb_wsj"
}

const au_comm_media_domains = ['bendigoadvertiser.com.au', 'bordermail.com.au', 'canberratimes.com.au', 'centralwesterndaily.com.au', 'dailyadvertiser.com.au', 'dailyliberal.com.au', 'examiner.com.au', 'illawarramercury.com.au', 'newcastleherald.com.au', 'northerndailyleader.com.au', 'portnews.com.au', 'standard.net.au', 'theadvocate.com.au', 'thecourier.com.au', 'westernadvocate.com.au'];
const au_news_corp_domains = ['adelaidenow.com.au', 'cairnspost.com.au', 'couriermail.com.au', 'dailytelegraph.com.au', 'geelongadvertiser.com.au', 'goldcoastbulletin.com.au', 'heraldsun.com.au', 'ntnews.com.au', 'theaustralian.com.au', 'thechronicle.com.au', 'themercury.com.au', 'townsvillebulletin.com.au', 'weeklytimesnow.com.au'];
const au_prov_news_domains = ['news-mail.com.au', 'frasercoastchronicle.com.au', 'gladstoneobserver.com.au', 'dailyexaminer.com.au', 'dailymercury.com.au', 'themorningbulletin.com.au', 'sunshinecoastdaily.com.au', 'gympietimes.com.au', 'qt.com.au', 'warwickdailynews.com.au'];
const br_folha_domains = ['folha.uol.com.br', 'blogfolha.uol.com.br'];
const ca_torstar_domains = ['niagarafallsreview.ca', 'stcatharinesstandard.ca', 'thepeterboroughexaminer.com', 'therecord.com', 'thespec.com', 'thestar.com', 'wellandtribune.ca'];
const de_funke_media_domains = ['abendblatt.de', 'braunschweiger-zeitung.de', 'morgenpost.de', 'nrz.de', 'otz.de', 'thueringer-allgemeine.de', 'tlz.de', 'waz.de', 'wp.de', 'wr.de'];
const de_madsack_domains = ['haz.de', 'kn-online.de', 'ln-online.de', 'lvz.de', 'maz-online.de', 'neuepresse.de', 'ostsee-zeitung.de'];
const economictimes_domains = ['economictimes.com', 'economictimes.indiatimes.com'];
const es_grupo_vocento_domains = ['diariosur.es', 'diariovasco.com', 'elcomercio.es', 'elcorreo.com', 'eldiariomontanes.es', 'elnortedecastilla.es', 'hoy.es', 'ideal.es', 'larioja.com', 'lasprovincias.es', 'laverdad.es', 'lavozdigital.es'];
const fi_alma_talent_domains = ['arvopaperi.fi', 'kauppalehti.fi', 'marmai.fi', 'mediuutiset.fi', 'mikrobitti.fi', 'talouselama.fi', 'tekniikkatalous.fi', 'tivi.fi', 'uusisuomi.fi'];
const fr_be_groupe_rossel_domains = ['aisnenouvelle.fr', 'courrier-picard.fr', 'lardennais.fr', 'lavoixdunord.fr', 'lecho.be', 'lesoir.be', 'lest-eclair.fr', 'liberation-champagne.fr', 'lunion.fr', 'nordeclair.fr', 'paris-normandie.fr', 'sudinfo.be'];
const fr_groupe_ebra_domains = ['bienpublic.com', 'dna.fr', 'estrepublicain.fr', 'lalsace.fr', 'ledauphine.com', 'lejsl.com', 'leprogres.fr', 'republicain-lorrain.fr', 'vosgesmatin.fr'];
const fr_groupe_la_depeche_domains = ['centrepresseaveyron.fr', 'ladepeche.fr', 'lindependant.fr', 'midi-olympique.fr', 'midilibre.fr', 'nrpyrenees.fr', 'petitbleu.fr'];
const it_ilmessaggero_domains = ['corriereadriatico.it', 'ilgazzettino.it', 'ilmattino.it', 'ilmessaggero.it', 'quotidianodipuglia.it'];
const nl_ad_region_domains = ['ad.nl', 'bd.nl', 'ed.nl', 'tubantia.nl', 'bndestem.nl', 'pzc.nl', 'destentor.nl', 'gelderlander.nl'];
const nl_mediahuis_region_domains = ['gooieneemlander.nl', 'haarlemsdagblad.nl', 'ijmuidercourant.nl', 'leidschdagblad.nl', 'noordhollandsdagblad.nl'];
const timesofindia_domains = ['timesofindia.com', 'timesofindia.indiatimes.com'];
const usa_crainsbiz_domains = ['chicagobusiness.com', 'crainscleveland', 'crainsdetroit', 'crainsnewyork.com'];
const usa_mcc_domains = ['bnd.com', 'charlotteobserver.com', 'fresnobee.com', 'kansas.com', 'kansascity.com', 'kentucky.com', 'miamiherald.com', 'newsobserver.com', 'sacbee.com', 'star-telegram.com', 'thestate.com', 'tri-cityherald.com'];
const usa_nymag_domains = ['curbed.com', 'grubstreet.com', 'nymag.com', 'thecut.com', 'vulture.com'];
const usa_tribune_domains = ['baltimoresun.com', 'chicagotribune.com', 'courant.com', 'dailypress.com', 'mcall.com', 'nydailynews.com', 'orlandosentinel.com', 'pilotonline.com', 'sun-sentinel.com'];
const usa_theathletic_domains = ['theathletic.com', 'theathletic.co.uk'];

var defaultSites_grouped_domains = Object.values(defaultSites);
var defaultSites_domains = defaultSites_grouped_domains.concat(au_comm_media_domains, au_news_corp_domains, au_prov_news_domains, br_folha_domains, ca_torstar_domains, de_funke_media_domains, de_madsack_domains, economictimes_domains, es_grupo_vocento_domains, fi_alma_talent_domains, fr_be_groupe_rossel_domains, fr_groupe_ebra_domains, fr_groupe_la_depeche_domains, it_ilmessaggero_domains, nl_ad_region_domains, nl_mediahuis_region_domains, timesofindia_domains, usa_crainsbiz_domains, usa_mcc_domains, usa_nymag_domains, usa_tribune_domains, usa_theathletic_domains);
